### ISSUE TITLE
@implement requires argument types which can be expressed as Symbols

### ISSUE THREAD

**Issue by KlausC** [tk3369/BinaryTraits.jl#26]
The specified argument type needs to be simple, for example no type parameter allowed

Right, I realized the missing feature as well. Currently, it needs to be a simple “symbol” for the parser to work. I guess it’s less convenient but you can define a constant and then use it in the interface. See the CartesianIndexing trait example.

**Comment by KlausC** [comment]
It would be really convenient to have that feature. I have a simple code change for that.

**Comment by tk3369** [comment]
Fixed by #33
