### ISSUE TITLE
Interface contracts should propagate to subtypes

### ISSUE THREAD

**Issue by tk3369** [tk3369/BinaryTraits.jl#30]
Consider this example: 

```julia
@trait Fly
@implement CanFly by liftoff()

abstract type Bird end
struct Duck <: Bird end
struct Chicken <: Bird end

@assign Bird with Fly
```

Since I assigned the abstract type `Bird` with the `Fly` trait and the `Fly` trait requires an interface contract `liftoff`, I expect both `Duck` and `Chicken` to satisfy that contract.  However:

```julia
julia> check(Duck)
✅ Duck has no interface contract requirements.
```

The interface check should traverse super-type tree and check all required contracts.

**Comment by KlausC** [comment]
Yes, I was missing that, too. I think it is easy to change that in `check` by additionally checking all supertypes of `Duck` (except `Any` - we should also disallow to assign an interface to `Any`).
In the case we support also parameter types, we must extend the checks to `UnionAll`
