### ISSUE TITLE
RFC: allow to assign parameterized types with traits

### ISSUE THREAD

**Issue by KlausC** [tk3369/BinaryTraits.jl#35]
It would be cool, if I could do:
```
@trait Sparse prefix Is,Not
@assign Adjoint{T,SparseVector{T}} where T with Sparse
```
Currently I have to use this work-around, because the `@assign` macro expects a `Symbol` as a first argument.

```julia
julia> @trait Sparse prefix Is,Not

julia> const AVS = Adjoint{<:Any, SparseVector}
Adjoint{var"#s54",SparseVector} where var"#s54"

julia> @assign AVS with Sparse
julia> @implement IsSparse by nnz()
julia> nnz(a::Adjoint{<:Any, SparseVector}) = nnz(a.data)
nnz (generic function with 2 methods)

julia> check(Adjoint{Float64, SparseVector})
✅ Adjoint{Float64,SparseVector} has implemented:
1. SparseTrait: IsSparse ⇢ nnz(::<Type>)::Any
```

**Comment by tk3369** [comment]
In the back of my mind, it doesn't seem too bad to make users define meaningful names for specific parametric types as I generally find the code more readable that way.  I do not oppose to supporting this though.

**Comment by KlausC** [comment]
I close this, because after #38 the issue is resolved.
